#ifndef DEMO_TAG_H
#define DEMO_TAG_H

typedef enum DEMO_SceneTag {
    DEMO_SCENETAG_ENTRY = 0,
    DEMO_SCENETAG_MENU = 1,
    DEMO_SCENETAG_SETTINGS = 2,

    DEMO_SCENETAG_COUNT
} DEMO_SceneTag;

typedef enum DEMO_Tag {
    DEMO_TAG_SCENE = 1 << 16,
    DEMO_TAG_SCENE_ENTRY = DEMO_TAG_SCENE | DEMO_SCENETAG_ENTRY,
    DEMO_TAG_SCENE_MENU = DEMO_TAG_SCENE | DEMO_SCENETAG_MENU,
} DEMO_Tag;

#endif // DEMO_TAG_H
