#ifndef GAME_TAG_H
#define GAME_TAG_H

typedef enum GAME_SceneTag {
    GAME_SCENETAG_ENTRY = 0,
    GAME_SCENETAG_MENU = 1,
    GAME_SCENETAG_SETTINGS = 2,

    GAME_SCENETAG_COUNT
} GAME_SceneTag;

typedef enum GAME_Tag {
    GAME_TAG_SCENE = 1 << 16,
    GAME_TAG_SCENE_ENTRY = GAME_TAG_SCENE | GAME_SCENETAG_ENTRY,
    GAME_TAG_SCENE_MENU = GAME_TAG_SCENE | GAME_SCENETAG_MENU,
} GAME_Tag;

#endif // GAME_TAG_H