#ifndef KEK_KEYBOARD_H
#define KEK_KEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

/*
This shit is stolen from SDL3 headers, but you can get it here:
https://usb.org/sites/default/files/hut1_5.pdf
*/
typedef enum KEK_scancode {
    KEK_SCANCODE_UNKNOWN = 0,

    KEK_SCANCODE_A = 4,
    KEK_SCANCODE_B = 5,
    KEK_SCANCODE_C = 6,
    KEK_SCANCODE_D = 7,
    KEK_SCANCODE_E = 8,
    KEK_SCANCODE_F = 9,
    KEK_SCANCODE_G = 10,
    KEK_SCANCODE_H = 11,
    KEK_SCANCODE_I = 12,
    KEK_SCANCODE_J = 13,
    KEK_SCANCODE_K = 14,
    KEK_SCANCODE_L = 15,
    KEK_SCANCODE_M = 16,
    KEK_SCANCODE_N = 17,
    KEK_SCANCODE_O = 18,
    KEK_SCANCODE_P = 19,
    KEK_SCANCODE_Q = 20,
    KEK_SCANCODE_R = 21,
    KEK_SCANCODE_S = 22,
    KEK_SCANCODE_T = 23,
    KEK_SCANCODE_U = 24,
    KEK_SCANCODE_V = 25,
    KEK_SCANCODE_W = 26,
    KEK_SCANCODE_X = 27,
    KEK_SCANCODE_Y = 28,
    KEK_SCANCODE_Z = 29,

    KEK_SCANCODE_1 = 30,
    KEK_SCANCODE_2 = 31,
    KEK_SCANCODE_3 = 32,
    KEK_SCANCODE_4 = 33,
    KEK_SCANCODE_5 = 34,
    KEK_SCANCODE_6 = 35,
    KEK_SCANCODE_7 = 36,
    KEK_SCANCODE_8 = 37,
    KEK_SCANCODE_9 = 38,
    KEK_SCANCODE_0 = 39,

    KEK_SCANCODE_RETURN = 40,
    KEK_SCANCODE_ESCAPE = 41,
    KEK_SCANCODE_BACKSPACE = 42,
    KEK_SCANCODE_TAB = 43,
    KEK_SCANCODE_SPACE = 44,

    KEK_SCANCODE_MINUS = 45,
    KEK_SCANCODE_EQUALS = 46,
    KEK_SCANCODE_LEFTBRACKET = 47,
    KEK_SCANCODE_RIGHTBRACKET = 48,
    KEK_SCANCODE_BACKSLASH = 49,
    KEK_SCANCODE_SEMICOLON = 51,
    KEK_SCANCODE_APOSTROPHE = 52,
    KEK_SCANCODE_GRAVE = 53,
    KEK_SCANCODE_COMMA = 54,
    KEK_SCANCODE_PERIOD = 55,
    KEK_SCANCODE_SLASH = 56,

    KEK_SCANCODE_CAPSLOCK = 57,

    KEK_SCANCODE_F1 = 58,
    KEK_SCANCODE_F2 = 59,
    KEK_SCANCODE_F3 = 60,
    KEK_SCANCODE_F4 = 61,
    KEK_SCANCODE_F5 = 62,
    KEK_SCANCODE_F6 = 63,
    KEK_SCANCODE_F7 = 64,
    KEK_SCANCODE_F8 = 65,
    KEK_SCANCODE_F9 = 66,
    KEK_SCANCODE_F10 = 67,
    KEK_SCANCODE_F11 = 68,
    KEK_SCANCODE_F12 = 69,

    KEK_SCANCODE_PRINTSCREEN = 70,
    KEK_SCANCODE_SCROLLLOCK = 71,
    KEK_SCANCODE_PAUSE = 72,
    KEK_SCANCODE_INSERT = 73,
    KEK_SCANCODE_HOME = 74,
    KEK_SCANCODE_PAGEUP = 75,
    KEK_SCANCODE_DELETE = 76,
    KEK_SCANCODE_END = 77,
    KEK_SCANCODE_PAGEDOWN = 78,
    KEK_SCANCODE_RIGHT = 79,
    KEK_SCANCODE_LEFT = 80,
    KEK_SCANCODE_DOWN = 81,
    KEK_SCANCODE_UP = 82,

    KEK_SCANCODE_NUMLOCK = 83,
    KEK_SCANCODE_KP_DIVIDE = 84,
    KEK_SCANCODE_KP_MULTIPLY = 85,
    KEK_SCANCODE_KP_MINUS = 86,
    KEK_SCANCODE_KP_PLUS = 87,
    KEK_SCANCODE_KP_ENTER = 88,
    KEK_SCANCODE_KP_1 = 89,
    KEK_SCANCODE_KP_2 = 90,
    KEK_SCANCODE_KP_3 = 91,
    KEK_SCANCODE_KP_4 = 92,
    KEK_SCANCODE_KP_5 = 93,
    KEK_SCANCODE_KP_6 = 94,
    KEK_SCANCODE_KP_7 = 95,
    KEK_SCANCODE_KP_8 = 96,
    KEK_SCANCODE_KP_9 = 97,
    KEK_SCANCODE_KP_0 = 98,
    KEK_SCANCODE_KP_PERIOD = 99,
    KEK_SCANCODE_NONUSBACKSLASH = 100,
    KEK_SCANCODE_LCTRL = 224,
    KEK_SCANCODE_LSHIFT = 225,
    KEK_SCANCODE_LALT = 226, /**< alt, option */
    KEK_SCANCODE_LGUI = 227, /**< windows, command (apple), meta */
    KEK_SCANCODE_RCTRL = 228,
    KEK_SCANCODE_RSHIFT = 229,
    KEK_SCANCODE_RALT = 230, /**< alt gr, option */
    KEK_SCANCODE_RGUI = 231, /**< windows, command (apple), meta */

    KEK_SCANCODE_SIZE = 512
} KEK_scancode;

#ifdef __cplusplus
}
#endif

#endif // KEK_KEYBOARD_H