#ifndef KEK_CONFIG_H
#define KEK_CONFIG_H

#ifndef KEK_MODEL_POOL_CAPACITY
#define KEK_MODEL_POOL_CAPACITY 8u
#endif

#ifndef KEK_TEXTURE_POOL_CAPACITY
#define KEK_TEXTURE_POOL_CAPACITY 8u
#endif

#ifndef KEK_POOL_MODEL_VERTS_MAX
#define KEK_POOL_MODEL_VERTS_MAX 1024u
#endif

#ifndef KEK_POOL_MODEL_FACES_MAX
#define KEK_POOL_MODEL_FACES_MAX 1024u
#endif

#ifndef KEK_POOL_MODEL_COLORS_MAX
#define KEK_POOL_MODEL_COLORS_MAX 1024u
#endif

#ifndef KEK_POOL_MODEL_UVS_MAX
#define KEK_POOL_MODEL_UVS_MAX 1024u
#endif

#ifndef KEK_POOL_TEXTURE_PIXELS_MAX
#define KEK_POOL_TEXTURE_PIXELS_MAX (256u * 256u)
#endif

#ifndef KEK_PALETTE_SHADING_LEVELS
#define KEK_PALETTE_SHADING_LEVELS 4u
#endif

#endif // KEK_CONFIG_H
